/** Domain actions checked by the centralized permission matrix. */
export const ACTIONS = [
  'organization:create',
  'organization:read',
  'organization:update',
  'member:list',
  'member:invite',
  'member:deactivate',
  'member:remove',
  'client:list',
  'client:read',
  'client:create',
  'client:update',
  'client:manage_members',
  'client:assign_operator',
  'client:unassign_operator',
  'audit:read',
  'elevation:request',
  'integration:list',
  'integration:create',
  'integration:rotate_secret',
  'integration:revoke',
  'event:replay',
  'lead:list',
  'lead:read',
  'dashboard:read',
  'workflow_run:read',
  'incident:read',
  'incident:manage',
  'report:read',
  'approval:create',
  'approval:read',
  'approval:decide',
  'approval:token_create',
  'approval:token_revoke',
] as const;

export type Action = (typeof ACTIONS)[number];
